In [2]:
import numpy as np

In [3]:
#ndarray 数组置换与轴对换 T transpose
arr = np.arange(40).reshape(5,-1)
print(arr.shape)
arr

(5, 8)


array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [4]:
arr1 = arr.transpose()
print(arr1.shape)
arr1

(8, 5)


array([[ 0,  8, 16, 24, 32],
       [ 1,  9, 17, 25, 33],
       [ 2, 10, 18, 26, 34],
       [ 3, 11, 19, 27, 35],
       [ 4, 12, 20, 28, 36],
       [ 5, 13, 21, 29, 37],
       [ 6, 14, 22, 30, 38],
       [ 7, 15, 23, 31, 39]])

In [5]:
arr2 = arr.T
print(arr2.shape)
arr2

(8, 5)


array([[ 0,  8, 16, 24, 32],
       [ 1,  9, 17, 25, 33],
       [ 2, 10, 18, 26, 34],
       [ 3, 11, 19, 27, 35],
       [ 4, 12, 20, 28, 36],
       [ 5, 13, 21, 29, 37],
       [ 6, 14, 22, 30, 38],
       [ 7, 15, 23, 31, 39]])