In [2]:
#矢量化: 数组不用循环即可对每个元素执行批量的算术运算操作，这个过程叫做矢量化，即用数组表达式代替循环的做法。
# 矢量化数组运算性能比纯Python方式快上一两个数据级。
import numpy as np

#数组与标量做算数运算
arr1 = np.array([1,2,3,4,5])
print(arr1+11)
print(arr1-2)
print(arr1*4)
print(arr1/3)
print(arr1/2.0)
print(2.0/arr1)
print(arr1**2)
print(2**arr1)

[12 13 14 15 16]
[-1  0  1  2  3]
[ 4  8 12 16 20]
[0.33333333 0.66666667 1.         1.33333333 1.66666667]
[0.5 1.  1.5 2.  2.5]
[2.         1.         0.66666667 0.5        0.4       ]
[ 1  4  9 16 25]
[ 2  4  8 16 32]


In [3]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[5.3,1.5,6.3],[4.3,2.7,2.3]])
print(arr1)
print(arr2)


[[1 2 3]
 [4 5 6]]
[[5.3 1.5 6.3]
 [4.3 2.7 2.3]]


In [4]:
print('arr1 + arr2')
print(arr1+arr2)
print('arr1 - arr2')
print(arr1 - arr2)
print('arr1 * arr2')
print(arr1*arr2)
print('arr1 / arr2')
print(arr1/arr2)
print('arr1 ** arr2')
print(arr1**arr2)

arr1 + arr2
[[6.3 3.5 9.3]
 [8.3 7.7 8.3]]
arr1 - arr2
[[-4.3  0.5 -3.3]
 [-0.3  2.3  3.7]]
arr1 * arr2
[[ 5.3  3.  18.9]
 [17.2 13.5 13.8]]
arr1 / arr2
[[0.18867925 1.33333333 0.47619048]
 [0.93023256 1.85185185 2.60869565]]
arr1 ** arr2
[[1.00000000e+00 2.82842712e+00 1.01359371e+03]
 [3.88023441e+02 7.71292328e+01 6.16237149e+01]]


In [6]:
#ndarray-数据的矩阵积
arr = np.array([
    [120, 60, 220],
    [115, 23, 201],
    [132, 48, 230]
])
arr

array([[120,  60, 220],
       [115,  23, 201],
       [132,  48, 230]])

In [9]:
arr2 = np.array([
    [12.34, 0.04],
    [204.56, 2.34],
    [9.89, 0.45]
])
arr2

array([[1.2340e+01, 4.0000e-02],
       [2.0456e+02, 2.3400e+00],
       [9.8900e+00, 4.5000e-01]])

In [10]:
arr.dot(arr2)

array([[15930.2 ,   244.2 ],
       [ 8111.87,   148.87],
       [13722.46,   221.1 ]])

In [11]:
np.dot(arr, arr2)

array([[15930.2 ,   244.2 ],
       [ 8111.87,   148.87],
       [13722.46,   221.1 ]])

In [14]:
arr[0,:]

array([120,  60, 220])

In [15]:
arr[0,:]*arr2[0,0]

array([1480.8,  740.4, 2714.8])

In [18]:
sum(arr[0,:]*arr2[:,0])

15930.2