In [1]:
import numpy as np


In [2]:
#ndarray-多维数组索引
arr = np.array([
    [
        [2, 3, 4, 5], [1, 3, 4, 9]  
    ],
    [
        [0, 3, 4, 8], [2, 4, 9, 4]
    ],
    [
        [1, 4, 5, 8], [2, 5, 6, 8]
    ],
    [
        [2, 3, 6, 8], [3, 4, 8, 9]
    ]
])

In [3]:
arr.shape

(4, 2, 4)

In [4]:
arr[3]

array([[2, 3, 6, 8],
       [3, 4, 8, 9]])

In [5]:
arr[3][1]

array([3, 4, 8, 9])

In [6]:
arr[3][1][2]

8

In [7]:
arr[3,1,2]

8

In [8]:
arr

array([[[2, 3, 4, 5],
        [1, 3, 4, 9]],

       [[0, 3, 4, 8],
        [2, 4, 9, 4]],

       [[1, 4, 5, 8],
        [2, 5, 6, 8]],

       [[2, 3, 6, 8],
        [3, 4, 8, 9]]])

In [9]:
#ndarray-数组的切片
arr[1]

array([[0, 3, 4, 8],
       [2, 4, 9, 4]])

In [10]:
arr[1][0]

array([0, 3, 4, 8])

In [11]:
arr[1][0][1:3]

array([3, 4])

In [12]:
arr[1][1][1:3]

array([4, 9])

In [13]:
arr[1,:,1:3]

array([[3, 4],
       [4, 9]])

In [14]:
#ndarray- 布尔类型索引
A = np.random.random((4,4))
print(A.shape)
A

(4, 4)


array([[0.75857157, 0.0074647 , 0.52843253, 0.5813808 ],
       [0.42129267, 0.17037393, 0.25620106, 0.53527675],
       [0.35859558, 0.84204946, 0.82366969, 0.84563427],
       [0.8295911 , 0.68259131, 0.0872456 , 0.16441196]])

In [15]:
B = A<0.5
print(B.shape)
B

(4, 4)


array([[False,  True, False, False],
       [ True,  True,  True, False],
       [ True, False, False, False],
       [False, False,  True,  True]])

In [16]:
C = A[B]
print(C.shape)
C

(7,)


array([0.0074647 , 0.42129267, 0.17037393, 0.25620106, 0.35859558,
       0.0872456 , 0.16441196])

In [18]:
names = np.array(['Gerry', 'Tom', 'John'])

In [31]:
scores = np.array([
    [98, 87, 86, 95],
    [58, 56, 54, 51],
    [78, 85, 85, 77]
])
classs = np.array(['语文', '数学', '英语', '科学'])
print('Gerry score is :',scores[names=='Gerry'].reshape((-1)))
print('Gerry 数学 score is:',scores[names=='Gerry'].reshape((-1))[classs=='数学'])
print('Gerry and tom scores')
print(scores[(names=='Gerry')|(names=='Tom')])
print('not Gerry and Tom student score')
print(scores[((names!='Gerry')&(names!='Tom'))])

Gerry score is : [98 87 86 95]
Gerry 数学 score is: [87]
Gerry and tom scores
[[98 87 86 95]
 [58 56 54 51]]
not Gerry and Tom student score
[[78 85 85 77]]


In [35]:
#ndarray-花式索引
arr = np.arange(32).reshape(8,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [36]:
print('get 0 3 5 rows data')
print(arr[[0,3,5]])

get 0 3 5 line data
[[ 0  1  2  3]
 [12 13 14 15]
 [20 21 22 23]]


In [37]:
print('get (0,0) (3,3), (5,2) index data')
print(arr[[0,3,5],[0,3,2]])

get (0,0) (3,3), (5,2) index data
[ 0 15 22]


In [41]:
print('get 0,3,5 rows 0,2,3 column data')
print(arr[[0,3,5]].T[[0,2,3]].T)
print()
print(arr[np.ix_([0,3,5],[0,2,3])])

get 0,3,5 rows 0,2,3 column data
[[ 0  2  3]
 [12 14 15]
 [20 22 23]]

[[ 0  2  3]
 [12 14 15]
 [20 22 23]]
