In [1]:
import numpy as np

In [5]:
arr = np.random.randint(1,8,size=(5,2))
arr

array([[4, 7],
       [1, 2],
       [5, 2],
       [2, 5],
       [2, 3]])

In [6]:
print('维度度数量:',arr.ndim)
print('数组形状:',arr.shape)
print('数组元素类型:',arr.dtype)
print('数组元素数量:',arr.size)

维度度数量: 2
数组形状: (5, 2)
数组元素类型: int64
数组元素数量: 10


In [8]:
a2 = arr.astype(float)
a2

array([[4., 7.],
       [1., 2.],
       [5., 2.],
       [2., 5.],
       [2., 3.]])

In [10]:
a2[3][1] = 10
print(a2,a2.dtype)
print(arr,arr.dtype)

[[ 4.  7.]
 [ 1.  2.]
 [ 5.  2.]
 [ 2. 10.]
 [ 2.  3.]] float64
[[4 7]
 [1 2]
 [5 2]
 [2 5]
 [2 3]] int64


In [11]:
d = np.array(['Python','Scala','Java','C'])
d

array(['Python', 'Scala', 'Java', 'C'], dtype='<U6')

In [12]:
d.dtype

dtype('<U6')

In [14]:
e = np.array(['Python','Scala','Java','C'],dtype='S3')
e

array([b'Pyt', b'Sca', b'Jav', b'C'], dtype='|S3')

In [16]:
a = np.arange(0,20,2)
print(a,a.size)

[ 0  2  4  6  8 10 12 14 16 18] 10


In [18]:
b = a.reshape(2,5)
print(b,b.size)
print(a,b)

[[ 0  2  4  6  8]
 [10 12 14 16 18]] 10
[ 0  2  4  6  8 10 12 14 16 18] [[ 0  2  4  6  8]
 [10 12 14 16 18]]


In [19]:
a.reshape(-1,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [20]:
a.reshape(5,-1)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [21]:
a.shape

(10,)

In [25]:
#reshape修改复制之后的数组形状，shape修改原数组形状
a.shape=(2,-1)
a

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [35]:
aa = np.arange(0,20,2)
bb = aa.reshape(5,2)
print(aa,bb)

[ 0  2  4  6  8 10 12 14 16 18] [[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]
 [16 18]]


直接使用reshape函数创建一个改变尺寸的新数组，原数组的shape保持不变，# 但是新数组和原数组共享一个内存空间，也就是修改任何一个数组中的值都会对另外一个产生影响，#  另外要求新数组的元素个数和原数组一致。


In [36]:
bb[3][1] = 66
print(aa,bb)

[ 0  2  4  6  8 10 12 66 16 18] [[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 66]
 [16 18]]
