In [12]:
import numpy as np

In [13]:
#创建一维数组
np.array([1,2,3])

array([1, 2, 3])

In [14]:
#创建二维数组
np.array([[1,2,3],[4,5,7]])

array([[1, 2, 3],
       [4, 5, 7]])

In [15]:
#创建三维数组
np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [16]:
#通过zeros创建
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
#通过ones创建
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
#通过empty创建
np.empty((4,3))

array([[ 2.31584178e+077, -1.73060688e-077,  8.39911598e-323],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000]])

In [19]:
#创建等差linspace
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [20]:
#创建等比logspace
np.logspace(1,10,num=10,base=2)

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

In [21]:
#通过random.randn创建
np.random.randn(3,4)

array([[-0.325836  ,  0.19867838,  0.28862874, -0.29989889],
       [-0.99849487, -0.77013873, -0.22812515, -2.17036253],
       [ 0.37799015, -0.61531638, -1.64332851, -0.96234896]])

In [23]:
#通过random.randint创建 范围 矩形大小 
np.random.randint(100,size=(3,4))

array([[62, 29, 20, 94],
       [39, 13, 57, 89],
       [59, 21, 77, 79]])